[package]
authors = ["<AUTHOR>"]
edition = "2018"
name = "my_zome"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "my_zome"

[dependencies]
serde = "1"
derive_more = "0"
chrono = {version = "0.4", features = ["serde"]}

hdk = "0.0.107"
holo_hash = { version = "0.0.7", features = ["encoding"] }
