[package]
edition = "2021"
name = "holochain_scaffolding_utils"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
build-fs-tree = "0.4.0"