[package]
edition = "2021"
name = "holochain_scaffolding_cli"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hc-scaffold"
path = "src/bin/hc-scaffold.rs"

[lib]
name = "holochain_scaffolding_cli"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
build-fs-tree = "0.4.0"
dialoguer = "0.10.2"
holochain_cli_bundle = {git = "https://github.com/holochain/holochain", rev = "c88b9faf3124b960cd38e370a92de463e43fffa8"}
holochain_scaffolding_definitions = {path = "../definitions"}
holochain_scaffolding_utils = {path = "../utils"}
holochain_types = {git = "https://github.com/holochain/holochain", rev = "c88b9faf3124b960cd38e370a92de463e43fffa8"}
holochain_util = {features = ["backtrace"], version = "0.0.12"}
mr_bundle = {git = "https://github.com/holochain/holochain", rev = "c88b9faf3124b960cd38e370a92de463e43fffa8"}
path-clean = "0.1.0"
serde_yaml = "0.8"
structopt = "0.3.11"
thiserror = "1.0.22"
tokio = {version = "1.11", features = ["full"]}

[dev-dependencies]
assert_cmd = "1.0"
